services:
  test:
    build: .
    command: bash -c "
        ruff check && \
        ruff linter && \
        make test"

  testv:
    build: .
    command: bash -c "
        ruff check && \
        ruff linter && \
        make test"
    volumes:
    -  .:/root/coco-tools

  bash:
    build: .
    command: bash

  bashv:
    build: .
    command: bash
    volumes:
    -  .:/root/coco-tools

